services:
  postgres:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    command: -p 8008
    ports:
      - 8008:8008
    networks:
      - database

  mariadb:
    image: mariadb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_TCP_PORT: 8009
    ports:
      - 8009:8009
    networks:
      - database

  mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_TCP_PORT: 8010
    ports:
      - 8010:8010
    networks:
      - database

networks:
  database:
    driver: bridge